name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Dependances
        run: |
          mkdir -p "$HOME/.cache/trivy"
          docker run --rm \
            -v "$PWD":/project \
            -v "$HOME/.cache/trivy":/root/.cache/ \
            aquasec/trivy:0.58.0 fs \
              --scanners vuln \
              --severity HIGH,CRITICAL \
              --ignore-unfixed \
              --exit-code 1 \
              /project
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Test Dockerfile
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock  -v "$HOME/.cache/trivy":/root/.cache/ aquasec/trivy:latest image --format json --severity HIGH,CRITICAL imgvulne:1.1 | jq -r '["TARGET","PACKAGE","INSTALLED","VULN","SEVERITY"],(.Results[]? as $r | $r.Vulnerabilities[]? | [$r.Target, .PkgName, .InstalledVersion, .VulnerabilityID, .Severity]) | @tsv' | column -t -s $'\t'
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
